-- =============================================================================
-- JJCAC - Jiu-Jitsu para Todos
-- Script SQL Completo para Implantacao no Supabase
-- Universidade Federal de Pernambuco (UFPE) - Projeto de Extensao
-- =============================================================================
--
-- INSTRUCOES DE USO:
-- 1. Crie um projeto no Supabase (https://supabase.com).
-- 2. Acesse o SQL Editor do painel do Supabase.
-- 3. Cole e execute este script na integra.
-- 4. Apos a execucao, configure as variaveis de ambiente do aplicativo
--    (.env.local) com a URL e ANON KEY do projeto Supabase criado.
--
-- IMPORTANTE: Este script deve ser executado em um projeto Supabase novo
-- (banco limpo). Ele cria todas as estruturas necessarias desde o inicio.
-- =============================================================================


-- ---------------------------------------------------------------------------
-- 1. EXTENSOES
-- ---------------------------------------------------------------------------
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";


-- ---------------------------------------------------------------------------
-- 2. TIPOS ENUMERADOS (ENUMS)
-- ---------------------------------------------------------------------------

CREATE TYPE public.user_role AS ENUM ('admin', 'monitor', 'aluno');

CREATE TYPE public.student_category AS ENUM ('frequente', 'academico', 'visitante');

CREATE TYPE public.event_type AS ENUM ('tournament', 'graduation', 'seminar', 'other');

CREATE TYPE public.announcement_importance AS ENUM ('info', 'warning', 'urgent');


-- ---------------------------------------------------------------------------
-- 3. TABELAS
-- ---------------------------------------------------------------------------

-- Perfis de usuario (vinculados a auth.users do Supabase)
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  full_name text NOT NULL,
  email text NOT NULL,
  role user_role NOT NULL DEFAULT 'aluno'::user_role,
  belt text DEFAULT 'Branca'::text,
  category student_category NOT NULL DEFAULT 'visitante'::student_category,
  institution text,
  enrollment_id text,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  gender text,
  phone text,
  emergency_contact text,
  ufpe_bond text,
  academic_level text,
  sexual_orientation text,
  gender_identity text,
  cpf text,

  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id) ON DELETE CASCADE,
  CONSTRAINT profiles_email_key UNIQUE (email),
  CONSTRAINT profiles_cpf_unique UNIQUE (cpf),
  CONSTRAINT profiles_full_name_not_empty CHECK (length(TRIM(BOTH FROM full_name)) > 0),
  CONSTRAINT profiles_email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
  CONSTRAINT profiles_cpf_format CHECK (cpf IS NULL OR cpf ~ '^\d{11}$')
);

-- Principios do Jiu-Jitsu (32 principios fundamentais)
CREATE TABLE public.principles (
  id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  number integer NOT NULL,
  title_pt text NOT NULL,
  title_en text NOT NULL,
  description text NOT NULL,
  category text,

  CONSTRAINT principles_pkey PRIMARY KEY (id),
  CONSTRAINT principles_number_key UNIQUE (number),
  CONSTRAINT principles_number_range CHECK (number >= 1 AND number <= 32),
  CONSTRAINT principles_title_pt_not_empty CHECK (length(TRIM(BOTH FROM title_pt)) > 0),
  CONSTRAINT principles_title_en_not_empty CHECK (length(TRIM(BOTH FROM title_en)) > 0)
);

-- Aulas registradas
CREATE TABLE public.workouts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  date date NOT NULL,
  technique_name text NOT NULL,
  technique_what text NOT NULL,
  technique_how text NOT NULL,
  technique_why text NOT NULL,
  principle_id integer NOT NULL,
  registered_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT workouts_pkey PRIMARY KEY (id),
  CONSTRAINT workouts_date_key UNIQUE (date),
  CONSTRAINT workouts_principle_id_fkey FOREIGN KEY (principle_id) REFERENCES principles(id),
  CONSTRAINT workouts_registered_by_fkey FOREIGN KEY (registered_by) REFERENCES profiles(id),
  CONSTRAINT workouts_technique_name_not_empty CHECK (length(TRIM(BOTH FROM technique_name)) > 0),
  CONSTRAINT workouts_technique_what_not_empty CHECK (length(TRIM(BOTH FROM technique_what)) > 0),
  CONSTRAINT workouts_technique_how_not_empty CHECK (length(TRIM(BOTH FROM technique_how)) > 0),
  CONSTRAINT workouts_technique_why_not_empty CHECK (length(TRIM(BOTH FROM technique_why)) > 0)
);

-- Registros de presenca (check-in)
CREATE TABLE public.attendance (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  workout_id uuid NOT NULL,
  checked_in_at timestamp with time zone NOT NULL DEFAULT now(),
  hygiene_confirmed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT attendance_pkey PRIMARY KEY (id),
  CONSTRAINT attendance_unique_per_workout UNIQUE (profile_id, workout_id),
  CONSTRAINT attendance_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  CONSTRAINT attendance_workout_id_fkey FOREIGN KEY (workout_id) REFERENCES workouts(id) ON DELETE CASCADE
);

-- Graduacoes (historico de faixas)
CREATE TABLE public.graduations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  previous_belt text NOT NULL,
  new_belt text NOT NULL,
  promoted_by uuid NOT NULL,
  promotion_date date NOT NULL DEFAULT CURRENT_DATE,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),

  CONSTRAINT graduations_pkey PRIMARY KEY (id),
  CONSTRAINT graduations_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
  CONSTRAINT graduations_promoted_by_fkey FOREIGN KEY (promoted_by) REFERENCES profiles(id)
);

-- Eventos (competicoes, seminarios, graduacoes)
CREATE TABLE public.events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  event_date timestamp with time zone NOT NULL,
  type event_type DEFAULT 'other'::event_type,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),

  CONSTRAINT events_pkey PRIMARY KEY (id),
  CONSTRAINT events_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE
);

-- Avisos e comunicados
CREATE TABLE public.announcements (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  message text NOT NULL,
  importance announcement_importance DEFAULT 'info'::announcement_importance,
  created_by uuid NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  updated_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),

  CONSTRAINT announcements_pkey PRIMARY KEY (id),
  CONSTRAINT announcements_created_by_fkey FOREIGN KEY (created_by) REFERENCES profiles(id) ON DELETE CASCADE
);

-- Notificacoes do sistema
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  profile_id uuid NOT NULL,
  title text NOT NULL,
  message text NOT NULL,
  link text,
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),

  CONSTRAINT notifications_pkey PRIMARY KEY (id),
  CONSTRAINT notifications_profile_id_fkey FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

-- Configuracoes globais do aplicativo
CREATE TABLE public.app_settings (
  key text NOT NULL,
  value text NOT NULL,

  CONSTRAINT app_settings_pkey PRIMARY KEY (key)
);

-- Assinaturas de notificacoes push (Web Push / VAPID)
CREATE TABLE public.push_subscriptions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  endpoint text NOT NULL,
  p256dh text NOT NULL,
  auth text NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),

  CONSTRAINT push_subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT push_subscriptions_endpoint_key UNIQUE (endpoint),
  CONSTRAINT push_subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);


-- ---------------------------------------------------------------------------
-- 4. INDICES DE PERFORMANCE
-- ---------------------------------------------------------------------------

-- profiles
CREATE INDEX idx_profiles_role ON public.profiles USING btree (role);
CREATE INDEX idx_profiles_belt ON public.profiles USING btree (belt);
CREATE INDEX idx_profiles_category ON public.profiles USING btree (category);
CREATE INDEX idx_profiles_is_active ON public.profiles USING btree (is_active) WHERE (is_active = true);
CREATE INDEX idx_profiles_cpf ON public.profiles USING btree (cpf) WHERE (cpf IS NOT NULL);

-- attendance
CREATE INDEX idx_attendance_profile ON public.attendance USING btree (profile_id);
CREATE INDEX idx_attendance_workout ON public.attendance USING btree (workout_id);
CREATE INDEX idx_attendance_profile_workout ON public.attendance USING btree (profile_id, workout_id);
CREATE INDEX idx_attendance_checked_in ON public.attendance USING btree (checked_in_at DESC);

-- workouts
CREATE INDEX idx_workouts_date ON public.workouts USING btree (date DESC);
CREATE INDEX idx_workouts_principle ON public.workouts USING btree (principle_id);
CREATE INDEX idx_workouts_registered_by ON public.workouts USING btree (registered_by);

-- graduations
CREATE INDEX idx_graduations_profile ON public.graduations USING btree (profile_id);
CREATE INDEX idx_graduations_promoted_by ON public.graduations USING btree (promoted_by);

-- events
CREATE INDEX idx_events_event_date ON public.events USING btree (event_date);
CREATE INDEX idx_events_type ON public.events USING btree (type);
CREATE INDEX idx_events_created_by ON public.events USING btree (created_by);

-- announcements
CREATE INDEX idx_announcements_created_at ON public.announcements USING btree (created_at);
CREATE INDEX idx_announcements_created_by ON public.announcements USING btree (created_by);

-- notifications
CREATE INDEX idx_notifications_profile_id ON public.notifications USING btree (profile_id);
CREATE INDEX idx_notifications_is_read ON public.notifications USING btree (is_read);
CREATE INDEX idx_notifications_created_at ON public.notifications USING btree (created_at);
CREATE INDEX idx_notifications_profile_unread ON public.notifications USING btree (profile_id, is_read) WHERE (is_read = false);

-- principles
CREATE INDEX idx_principles_category ON public.principles USING btree (category);


-- ---------------------------------------------------------------------------
-- 5. FUNCOES AUXILIARES
-- ---------------------------------------------------------------------------

-- Verifica se o usuario autenticado e administrador
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- Verifica se o usuario autenticado e administrador ou monitor
CREATE OR REPLACE FUNCTION public.is_admin_or_monitor()
RETURNS boolean
LANGUAGE sql
SECURITY DEFINER
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role IN ('admin', 'monitor')
  );
$$;

-- Atualiza campo updated_at automaticamente (versao timezone UTC)
CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = timezone('utc'::text, now());
  RETURN NEW;
END;
$$;

-- Atualiza campo updated_at automaticamente (versao simples)
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- Cria perfil automaticamente quando um novo usuario se registra
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  INSERT INTO public.profiles (
    id, full_name, email, role, category, gender, institution, enrollment_id,
    phone, emergency_contact, ufpe_bond, academic_level, sexual_orientation, gender_identity
  )
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data->>'full_name', 'Novo Aluno'),
    NEW.email,
    COALESCE((NEW.raw_user_meta_data->>'role')::public.user_role, 'aluno'),
    COALESCE((NEW.raw_user_meta_data->>'category')::public.student_category, 'visitante'),
    NEW.raw_user_meta_data->>'gender',
    NEW.raw_user_meta_data->>'institution',
    NEW.raw_user_meta_data->>'enrollment_id',
    NEW.raw_user_meta_data->>'phone',
    NEW.raw_user_meta_data->>'emergency_contact',
    NEW.raw_user_meta_data->>'ufpe_bond',
    NEW.raw_user_meta_data->>'academic_level',
    NEW.raw_user_meta_data->>'sexual_orientation',
    NEW.raw_user_meta_data->>'gender_identity'
  );
  RETURN NEW;
END;
$$;

-- Sincroniza delecao de perfil com auth.users
CREATE OR REPLACE FUNCTION public.handle_deleted_profile()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  DELETE FROM auth.users WHERE id = OLD.id;
  RETURN OLD;
END;
$$;


-- ---------------------------------------------------------------------------
-- 6. TRIGGERS
-- ---------------------------------------------------------------------------

-- Criacao automatica de perfil ao registrar usuario
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Sincronizacao de delecao de perfil
CREATE TRIGGER on_profile_deleted
  AFTER DELETE ON profiles
  FOR EACH ROW EXECUTE FUNCTION handle_deleted_profile();

-- Atualizacao automatica de updated_at
CREATE TRIGGER set_updated_at_profiles
  BEFORE UPDATE ON profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER set_updated_at_workouts
  BEFORE UPDATE ON workouts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER set_updated_at_graduations
  BEFORE UPDATE ON graduations
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER set_updated_at_events
  BEFORE UPDATE ON events
  FOR EACH ROW EXECUTE FUNCTION handle_updated_at();

CREATE TRIGGER set_updated_at_announcements
  BEFORE UPDATE ON announcements
  FOR EACH ROW EXECUTE FUNCTION handle_updated_at();


-- ---------------------------------------------------------------------------
-- 7. ROW LEVEL SECURITY (RLS)
-- ---------------------------------------------------------------------------

-- Habilitar RLS em todas as tabelas
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.principles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.workouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.attendance ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.graduations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

-- Policies: profiles
CREATE POLICY profiles_select_policy ON public.profiles FOR SELECT
  USING (is_admin_or_monitor() OR (auth.uid() = id));
CREATE POLICY profiles_insert_policy ON public.profiles FOR INSERT
  WITH CHECK ((auth.uid() = id) OR is_admin());
CREATE POLICY profiles_update_policy ON public.profiles FOR UPDATE
  USING (is_admin() OR (auth.uid() = id));
CREATE POLICY profiles_delete_policy ON public.profiles FOR DELETE
  USING (is_admin());

-- Policies: principles
CREATE POLICY principles_select_policy ON public.principles FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY principles_insert_policy ON public.principles FOR INSERT
  WITH CHECK (is_admin());
CREATE POLICY principles_update_policy ON public.principles FOR UPDATE
  USING (is_admin());
CREATE POLICY principles_delete_policy ON public.principles FOR DELETE
  USING (is_admin());

-- Policies: workouts
CREATE POLICY workouts_select_policy ON public.workouts FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY workouts_insert_policy ON public.workouts FOR INSERT
  WITH CHECK (is_admin_or_monitor());
CREATE POLICY workouts_update_policy ON public.workouts FOR UPDATE
  USING (is_admin_or_monitor());
CREATE POLICY workouts_delete_policy ON public.workouts FOR DELETE
  USING (is_admin());

-- Policies: attendance
CREATE POLICY attendance_select_policy ON public.attendance FOR SELECT
  USING (is_admin_or_monitor() OR (auth.uid() = profile_id));
CREATE POLICY attendance_insert_policy ON public.attendance FOR INSERT
  WITH CHECK ((auth.uid() = profile_id) OR is_admin_or_monitor());
CREATE POLICY attendance_update_policy ON public.attendance FOR UPDATE
  USING (is_admin());
CREATE POLICY attendance_delete_policy ON public.attendance FOR DELETE
  USING (is_admin());

-- Policies: graduations
CREATE POLICY graduations_select_policy ON public.graduations FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY "Todos os usuarios autenticados podem ver as graduacoes" ON public.graduations FOR SELECT
  TO authenticated USING (true);
CREATE POLICY graduations_insert_policy ON public.graduations FOR INSERT
  WITH CHECK (is_admin());
CREATE POLICY graduations_update_policy ON public.graduations FOR UPDATE
  USING (is_admin());
CREATE POLICY graduations_delete_policy ON public.graduations FOR DELETE
  USING (is_admin());

-- Policies: events
CREATE POLICY "Leitura de eventos liberada para autenticados" ON public.events FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY "Apenas admin modifica eventos" ON public.events FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'::user_role));

-- Policies: announcements
CREATE POLICY "Leitura de avisos liberada para autenticados" ON public.announcements FOR SELECT
  USING (auth.uid() IS NOT NULL);
CREATE POLICY "Apenas admin modifica avisos" ON public.announcements FOR ALL
  USING (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'::user_role));

-- Policies: notifications
CREATE POLICY "Usuarios leem apenas suas notificacoes" ON public.notifications FOR SELECT
  USING (auth.uid() = profile_id);
CREATE POLICY "Admins inserem notificacoes para qualquer um" ON public.notifications FOR INSERT
  WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE profiles.id = auth.uid() AND profiles.role = 'admin'::user_role));
CREATE POLICY "Usuarios marcam suas notificacoes como lidas" ON public.notifications FOR UPDATE
  USING (auth.uid() = profile_id);
CREATE POLICY "Usuarios deletam suas notificacoes" ON public.notifications FOR DELETE
  USING (auth.uid() = profile_id);

-- Policies: app_settings
CREATE POLICY "Admin gerencia app_settings" ON public.app_settings FOR ALL
  USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "Admin le todas as configuracoes" ON public.app_settings FOR SELECT
  USING (is_admin());
CREATE POLICY "Autenticados leem chave publica" ON public.app_settings FOR SELECT
  TO authenticated USING (key <> 'vapid_private_key'::text);

-- Policies: push_subscriptions
CREATE POLICY "Usuarios podem ver suas proprias assinaturas" ON public.push_subscriptions FOR SELECT
  USING (auth.uid() = user_id);
CREATE POLICY "Usuarios podem inserir suas proprias assinaturas" ON public.push_subscriptions FOR INSERT
  WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Usuarios podem atualizar suas proprias assinaturas" ON public.push_subscriptions FOR UPDATE
  USING (auth.uid() = user_id);
CREATE POLICY "Usuarios podem deletar suas proprias assinaturas" ON public.push_subscriptions FOR DELETE
  USING (auth.uid() = user_id);
CREATE POLICY "Admin e monitor leem todas subscriptions" ON public.push_subscriptions FOR SELECT
  USING (is_admin_or_monitor());
CREATE POLICY "Admin deleta subscriptions expiradas" ON public.push_subscriptions FOR DELETE
  USING (is_admin_or_monitor());


-- ---------------------------------------------------------------------------
-- 8. DADOS INICIAIS (SEED) - 32 Principios do Jiu-Jitsu
-- ---------------------------------------------------------------------------

INSERT INTO public.principles (number, title_pt, title_en, description, category) VALUES
(1, 'Distancia', 'Distance Management', 'No tatame: Manter o adversario longe o suficiente para nao ser atingido, mas perto o suficiente para agir. Na vida: Saber impor limites saudaveis em relacionamentos e negocios para manter o controle da situacao.', 'Fundamento'),
(2, 'Guarda', 'Guard Retention', 'No tatame: A capacidade de manter suas pernas entre voce e o adversario para se defender. Na vida: Proteger seus recursos mais valiosos e ter um sistema de defesa solido contra ameacas externas.', 'Defesa'),
(3, 'Espaco', 'Space Creation', 'No tatame: Afastar o adversario para criar oportunidades de escape ou ataque. Na vida: Criar margem financeira, de tempo ou emocional para conseguir pensar com clareza em situacoes de crise.', 'Defesa'),
(4, 'Fechamento', 'Space Closure', 'No tatame: Eliminar os espacos vazios para restringir a mobilidade do oponente. Na vida: Fechar brechas de ineficiencia, diminuir distracoes e focar intensamente nos seus objetivos mais importantes.', 'Ataque'),
(5, 'Base', 'Base Establishment', 'No tatame: Distribuir o peso e se posicionar para nao ser desequilibrado. Na vida: Construir alicerces solidos (financeiros, mentais e morais) para nao ser derrubado pelas tempestades do cotidiano.', 'Fundamento'),
(6, 'Postura', 'Posture Alignment', 'No tatame: Manter a coluna alinhada e a cabeca erguida para ter maxima forca. Na vida: Ter clareza de principios e agir com retidao, mantendo sua integridade mesmo sob extrema pressao.', 'Fundamento'),
(7, 'Estrutura', 'Frame Construction', 'No tatame: Usar os ossos (frames) em vez de musculos para suportar peso sem cansar. Na vida: Criar sistemas e rotinas automaticas que sustentem seu crescimento sem depender apenas da sua forca de vontade.', 'Defesa'),
(8, 'Kuzushi', 'Off-Balancing', 'No tatame: Quebrar a postura e o equilibrio do oponente antes de atacar. Na vida: Encontrar o momento exato em que um problema ou concorrente esta vulneravel para agir com o menor esforco.', 'Ataque'),
(9, 'Alavanca', 'Leverage Utilization', 'No tatame: Usar pontos de apoio e multiplicar a forca mecanica contra articulacoes. Na vida: O principio da alavancagem - usar ferramentas, equipe ou capital para obter resultados muito maiores que o seu esforco individual.', 'Fundamento'),
(10, 'Cunha', 'Wedge Insertion', 'No tatame: Inserir parte do seu corpo como uma cunha para impedir a movimentacao. Na vida: Inserir pequenos habitos positivos de forma implacavel para mudar gradualmente a direcao da sua vida.', 'Ataque'),
(11, 'Gancho', 'Hook Application', 'No tatame: Usar pes e pernas para prender e controlar o oponente sem usar as maos. Na vida: Estabelecer pontos de conexao sutis em negociacoes e networking, mantendo influencia sem parecer autoritario.', 'Controle'),
(12, 'Angulo', 'Angle Creation', 'No tatame: Sair da linha central de ataque para achar brechas indefensaveis. Na vida: Buscar perspectivas diferentes, inovar e atacar problemas por angulos que ninguem mais esta olhando.', 'Ataque'),
(13, 'Centro de Gravidade', 'Center of Gravity', 'No tatame: Manipular o seu peso e o do adversario para maximizar o controle. Na vida: Saber exatamente onde esta sua principal fonte de energia e proposito, mantendo-se centrado.', 'Fundamento'),
(14, 'Conexao', 'Connection Maintenance', 'No tatame: Manter contato fisico constante para "ler" os movimentos do oponente. Na vida: Criar lacos fortes e comunicacao constante com seu time e clientes para antecipar necessidades e problemas.', 'Controle'),
(15, 'Contencao', 'Containment', 'No tatame: Limitar as opcoes de fuga do adversario, direcionando-o para uma armadilha. Na vida: Controlar o escopo de projetos e focar recursos em um unico caminho, evitando a dispersao de energia.', 'Controle'),
(16, 'Redirecionamento', 'Redirection', 'No tatame: Usar a forca do oponente contra ele proprio, em vez de resistir. Na vida: Nao bater de frente com criticas ou crises; redirecione a energia negativa para gerar motivacao e inovacao.', 'Filosofia'),
(17, 'Velocidade', 'Velocity Control', 'No tatame: Alterar o ritmo da luta para confundir e cansar o oponente. Na vida: Saber quando acelerar a execucao de projetos e quando desacelerar para analisar e planejar.', 'Estrategia'),
(18, 'Pressao', 'Pressure Application', 'No tatame: Aplicar peso de forma focada para esgotar a resistencia. Na vida: Aplicar consistencia implacavel ao longo do tempo (pressao constante) ate que grandes obstaculos cedam.', 'Ataque'),
(19, 'Isolamento', 'Isolation', 'No tatame: Isolar um membro do corpo do adversario para focar todo seu ataque nele. Na vida: O poder do hiperfoco. Isolar a variavel mais importante do seu negocio e ataca-la com toda a sua atencao.', 'Ataque'),
(20, 'Sacrificio', 'Sacrifice', 'No tatame: Desistir de uma posicao menor para conquistar uma vantagem maior (ex: isca). Na vida: O principio da escolha e renuncia. Abrir mao de prazeres imediatos para conquistar a vitoria de longo prazo.', 'Estrategia'),
(21, 'Fluidez', 'Flow', 'No tatame: Transitar suavemente entre posicoes sem usar forca bruta, adaptando-se. Na vida: "Be water, my friend". Ter a mente aberta para mudar estrategias instantaneamente quando as circunstancias exigirem.', 'Filosofia'),
(22, 'Tempo', 'Timing', 'No tatame: Executar o golpe no momento exato de vulnerabilidade. Na vida: Timing e tudo no mercado. Saber a hora certa de lancar um produto, pedir um aumento ou iniciar um novo ciclo.', 'Estrategia'),
(23, 'Precisao', 'Precision', 'No tatame: A tecnica perfeita, no lugar perfeito, nao exige forca. Na vida: Atingir a maestria. Fazer o trabalho focado que gera 80%% dos resultados com 20%% do esforco.', 'Fundamento'),
(24, 'Eficiencia', 'Efficiency', 'No tatame: Gastar o minimo de energia para obter o maximo de resultado. Na vida: Eliminar processos redundantes, otimizar sua agenda e nao desperdicar energia com o que esta fora do seu controle.', 'Filosofia'),
(25, 'Acao e Reacao', 'Action-Reaction', 'No tatame: Induzir uma reacao no oponente para abrir a porta para o ataque real. Na vida: Plantar ideias sutilmente e prever como o mercado ou uma pessoa reagira, estando um passo a frente.', 'Estrategia'),
(26, 'Adaptacao', 'Adaptation', 'No tatame: Ajustar seu jogo em milissegundos conforme o oponente muda a estrategia. Na vida: Sobrevivem os mais adaptaveis. Se a tecnologia ou o mundo muda, voce recalcula a rota sem lamentacoes.', 'Filosofia'),
(27, 'Resiliencia', 'Resilience', 'No tatame: Suportar situacoes desconfortaveis (ficar por baixo) mantendo a calma. Na vida: A capacidade de apanhar da vida, perder dinheiro ou sofrer reveses, levantar e continuar lutando mentalmente forte.', 'Filosofia'),
(28, 'Paciencia', 'Patience', 'No tatame: Esperar calmamente que o oponente se canse ou cometa um erro. Na vida: Entender que grandes construcoes levam tempo. Nao force o processo, mas esteja preparado para a oportunidade.', 'Filosofia'),
(29, 'Respiracao', 'Breathing Control', 'No tatame: Respirar corretamente para manter a frequencia cardiaca baixa sob pressao. Na vida: Inteligencia emocional. Acalmar a mente antes de tomar decisoes criticas ou em situacoes de panico.', 'Fundamento'),
(30, 'Percepcao', 'Awareness', 'No tatame: Ter consciencia plena de tudo que acontece ao redor (posicao, pegadas). Na vida: Visao sistemica. Observar tendencias invisiveis e entender as engrenagens ocultas da sociedade e do mercado.', 'Estrategia'),
(31, 'Mentalidade', 'Mindset', 'No tatame: Achar o conforto no desconforto e recusar-se a desistir da luta. Na vida: A mentalidade inquebravel. O sucesso e, na maioria das vezes, uma questao de pura teimosia positiva e atitude mental.', 'Filosofia'),
(32, 'Comunidade', 'Community', 'No tatame: Ninguem chega a faixa preta sozinho. Seus parceiros forjam sua forca. Na vida: O poder do ambiente. Voce e a media das pessoas com quem convive. Construa uma tribo que te eleve.', 'Filosofia');


-- ---------------------------------------------------------------------------
-- FIM DO SCRIPT
-- ---------------------------------------------------------------------------
